### PR TITLE
Coordinated Universal Time support

### PR DESCRIPTION
**Pull request by craigmoliver**
Added support in configuration to set whether or not Coordinated Universal Time should be used.

### CODE REVIEW

**Comment by craigmoliver** [comment]
Hey all, my firm is global and all date/time stamps we store must be UTC. I modified your code to suit our needs. Hopefully you'll see this simple addition as useful and include it.

**Comment by JonathanMagnan** [comment]
Hello @craigmoliver ,

Thank you for your pull,

Yes, I believe that's a great addition.

We will review your pull and probably merge it at the end of the week.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by craigmoliver** [comment]
Thanks! Glad to hear. The code is working great so far. I may have more coming. Great work to all on this library.

**Comment by JonathanMagnan** [comment]
Hello @craigmoliver ,

The pull has been merged, we have made some small modification such as renaming the property to `UseUtcDateTime` since it seems to be the option name people normally use.

Let me know if everything works as expected.

Just to let you know, we currently focus more our time on EF Classic: https://entityframework-classic.net/

So if you have some idea for this library, they will be also very welcome ;)

Best Regards,

Jonathan

**Pull request merged**
