### PR TITLE
Implemented in memory check for Effort in EF6

### PR DESCRIPTION
**Pull request by naldorp**
Hi,

I was trying to use this extension on a project in EF6 with Effort.EF6 and I was getting a lot of exceptions. This PR is fixing all these problems, I basically created a condition to check if the connection is a EffortConnection. This way the unit test should not break.

I know that this could not be the best solution for this case and you can reject this PR if you want. Also, I can create an issue regarding this problem so we can discuss the best solution.

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @naldorp ,

The problem with your pull is you reference some packages:

- Effort.dll
- NMemory.dll

Which our library cannot depend on.

If you want, try to make this pull but without reference.

By example,

This line:
```csharp
return q.GetDbContext().Database.Connection is Effort.Provider.EffortConnection;`
```

should be something like

```csharp
return q.GetDbContext().Database.Connection.GetType().FullName == "Effort.Provider.EffortConnection";
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Just let me know if you are stuck somewhere btw, I will be happy to help you or merge what you have done and complete this request.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @naldorp ,

Thank you ;) I will review this merge and if there is no error, it will get merge this weekend.

Best Regards,

Jonathan

**Comment by naldorp** [comment]
👍  Dependencies removed.

**Comment by JonathanMagnan** [comment]
Hello @naldorp ,

The v1.6.18 has been released.

Batch Delete && Batch Update should now be compatible with effort using the Pull you provided.

Best Regards,

Jonathan

**Pull request merged**
