### PR TITLE
We need to use the property value, not the C# property name to build …

### PR DESCRIPTION
**Pull request by TheFireCookie**
This solve the issue https://github.com/zzzprojects/EntityFramework-Plus/issues/483

### CODE REVIEW

**Comment by JonathanMagnan** [comment]
Hello @TheFireCookie ,

Thank you for the pull.

However, something feels weird. I believe the `Item1` was not here by mistake but because Entity Framework will alias the column name to the property name and that's why the code is currently here.

Perhaps it was true for some older EF Core version and that has been modified in a later version?

Anyway, we will look at it and make sure that everything still works before merging this pull.

**Comment by TheFireCookie** [comment]
But here you are generating direct SQL Code if I'm not mistaken.
In the older, you were doing directly this
` primaryKeys = string.Join(Environment.NewLine + "AND ", columnKeys.Select(x => string.Concat("A.\"", x, "\" = B.\"", x, "\"")));`
And columnKeys what this:
`var columnNameProperty = mappingProperty.GetType().GetProperty("ColumnName", BindingFlags.Public | BindingFlags.Instance);
                    columnKeys.Add((string)columnNameProperty.GetValue(mappingProperty));`
Meaning it was directly always "Item2" of the new code.
I think the bug is there for a long time but maybe it doens't occur as often. But I'll let you be the judge 👍

**Comment by pitming** [comment]
Got the same bug here and Pull Request from @TheFireCookie fixed the problem on my side...

**Comment by JonathanMagnan** [comment]
Hello @TheFireCookie, @pitming  ,

Sorry for the long waiting.

A new version has been released v1.9.0, it's a hybrid of your fix.

From our test, we found out that sometimes the relational name is used and sometimes the property name is used (via an alias) depending on the number of the primary key of your entities.

I'm not sure if we are missing some case but we hope that it will fix your case.

Let me know if the latest version works correctly.

**Comment by JonathanMagnan** [comment]
(We will close this pull since we can continue the discussion on the issue #483)

**Pull request closed without merging**
